version: 2.1

jobs:
    build:
        docker:
            - image: cimg/node:16.14.2
        steps:
            - checkout
            - run:
                  name: check package.json
                  command: echo "$(<web/package.json)"
            - run:
                  name: install
                  command: npm install --prefix ./web
            - run:
                  name: build
                  command: npm run build --prefix ./web

workflows:
    orb-free-workflow:
        jobs:
            - build
